version: '3'
services:

  elasticsearch_code:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch_code
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sgd-esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana_code
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - KIBANA_AUTOCOMPLETETERMINATEAFTER=10000000
    ports:
      - 5601:5601
    links:
      - elasticsearch_code:elasticsearch
    networks:
      - esnet
    depends_on:
      - elasticsearch_code

volumes:
  sgd-esdata:

networks:
  esnet:

